apiVersion: v1
kind: Pod
metadata:
  name: alpine-2
  labels:
    app: app2
spec:
  containers:
    - name: alpine2
      image: alpine:latest
      command: ["sleep", "infinity"]
  
  tolerations:
  - key: "app2"
    operator: "Equal"
    value: "Purple"
    effect: "NoExecute"