apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: cluster-serviceaccount-role-binding
subjects:
- kind: User
  name: cluster-service-account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-administrator
  apigroup: rbac.authorization.k8s.io  