apiVersion: v1 
kind: ServiceAccount
metadata:
  name: prom-1
---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  serviceAccountName: prom-1
  containers:
    - name: prometheus
      image: prom/prometheus:main
      command: ["sleep", "infinity"]