apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: poweruser
rules: 
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "update"]
- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["list", "get", "update"]